DROP INDEX universal.idx_entry_attribute_attribute_id;
DROP INDEX universal.idx_entry_attribute_code_system;
DROP INDEX universal.idx_entry_attribute_code_value;
DROP INDEX universal.idx_entry_attribute_date_value;
DROP INDEX universal.idx_entry_attribute_entry_id;
DROP INDEX universal.idx_entry_attribute_text_value;
