ALTER TABLE universal.entry_attribute DROP CONSTRAINT entry_attribute_pkey;
ALTER TABLE universal.entry_attribute DROP CONSTRAINT entry_attribute_attribute_id_fkey;
ALTER TABLE universal.entry_attribute DROP CONSTRAINT entry_attribute_entry_id_fkey;
