TRUNCATE universal.clinic RESTART IDENTITY CASCADE;
TRUNCATE universal.practitioner RESTART IDENTITY CASCADE;
TRUNCATE universal.patient RESTART IDENTITY CASCADE;
TRUNCATE universal.patient_practitioner RESTART IDENTITY CASCADE;
TRUNCATE universal.entry RESTART IDENTITY CASCADE;
TRUNCATE universal.entry_attribute RESTART IDENTITY CASCADE;
TRUNCATE universal.state RESTART IDENTITY CASCADE;
